version: '3'
services:    
    db-postgres-compose:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "^4vBdKzF28Ab"
        ports:
            - "15432:5432"
        volumes:
            - F:/VOLUMES/PostgreSQL:/var/lib/postgresql/data 
        networks:
            - db-network
        
    client-pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "dba@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "^4vBdKzF28Ab"
        ports:
            - "16543:80"
        depends_on:
            - db-postgres-compose
        networks:
            - db-network

    default-arch:
        container_name: default-arch-microservice
        image: ms-products-img:latest
        ports:
            - 8091:8091
        depends_on:
            - client-pgadmin-compose
        networks:
            - default-network
            - db-network
            - monit
        healthcheck:
            test: "curl -sS http://default-arch:8091/actuator/health"
            interval: 1s
            timeout: 30s            
            retries: 60       
    prometheus-java:
        image: prom/prometheus:latest
        container_name: prometheus-java
        restart: unless-stopped
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/prometheus_data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
        ports:
        - 9090:9090
        networks:
        - monit
        - default-network
        depends_on:
        - default-arch

    service-register-ms:
        image: service-register:latest
        container_name: service-register-ms
        restart: unless-stopped
        ports:
            - 9091:9081
        depends_on:
            - prometheus-java
        networks:
            - default-network
            - db-network
            - monit
        healthcheck:
            test: "curl -sS http://service-register-ms:9091/actuator/health"
            interval: 1s
            timeout: 30s            
            retries: 60 
        

networks:
    default-network:
        driver: bridge
    db-network:
        driver: bridge
    monit:
        driver: bridge

    