version: '3'
services:    
    db-postgres:
        container_name: db-postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: "^4vBdKzF28Ab"
        ports:
            - "15432:5432"
        volumes:
            - F:/VOLUMES/PostgreSQL:/var/lib/postgresql/data 
        networks:
            - db-network
        
    client-pgadmin:
        image: dpage/pgadmin4
        container_name: client-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "dba@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "^4vBdKzF28Ab"
        ports:
            - "16543:80"
        depends_on:
            - db-postgres
        networks:
            - db-network

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        ports:
            - 4000:9090
        networks:
            - monit
            - default-network
        depends_on:
            - client-pgadmin
    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - ./grafana:/var/lib/grafana
        restart: unless-stopped
        ports:
            - 3000:3000
        networks:
            - monit
            - default-network            
        depends_on:
            - prometheus
            
    ms-service-register:
        image: service-register-img:latest
        container_name: ms-service-register
        restart: unless-stopped
        ports:
            - 9090:9090
        depends_on:
            - grafana
        networks:
            - default-network
            - db-network
            - monit
        healthcheck:
            test: "curl -sS http://ms-service-register:9090/actuator/health"
            interval: 1s
            timeout: 30s
            retries: 60

    ms-gateway:
        image: ms-gateway-img:latest
        container_name: ms-gateway
        restart: unless-stopped
        ports:
            - 9091:9091
        depends_on:
            - ms-service-register
        networks:
            - default-network
            - db-network
            - monit
        healthcheck:
            test: "curl -sS http://ms-gateway:9091/actuator/health"
            interval: 1s
            timeout: 30s
            retries: 60
    ms-products:
        container_name: ms-products
        image: ms-products-img:latest
        ports:
            - 9092:9092
        depends_on:
            - ms-gateway
        networks:
            - default-network
            - db-network
            - monit
        healthcheck:
            test: "curl -sS http://ms-products:9092/actuator/health"
            interval: 1s
            timeout: 30s            
            retries: 60
    
networks:
    default-network:
        driver: bridge
    db-network:
        driver: bridge
    monit:
        driver: bridge   